version: '3'

services:
  postservice.gstaad:
    build:
      context: src/postservice
      dockerfile: Dockerfile
    ports:
      - 9202:8080
    env_file: "src/postservice/.env"
    environment:
      - PORT=8080
    healthcheck:
      test: ["CMD-SHELL", "/bin/grpc_health_probe -addr=:8080 || exit 1"]
      interval: 5s
      timeout: 2s
      retries: 2
  postservice-gw.gstaad:
    build:
      context: src/postservice
      dockerfile: ../../tools/envoy/Dockerfile
      args:
        - UPSTREAM=postservice.gstaad
    ports:
      - 9200:80
      - 9201:8081
    env_file: "src/postservice/.env"
    healthcheck:
      interval: 5s
      timeout: 2s
      retries: 4
  userservice.gstaad:
    build:
      context: src/userservice
      dockerfile: Dockerfile
    ports:
      - 9102:8080
    env_file: "src/userservice/.env"
    environment:
      - PORT=8080
      - POSTSERVICE=dns:///postservice.gstaad:8080
    healthcheck:
      test: ["CMD-SHELL", "/bin/grpc_health_probe -addr=:8080 || exit 1"]
      interval: 5s
      timeout: 2s
      retries: 2
  userservice-gw.gstaad:
    build:
      context: src/userservice
      dockerfile: ../../tools/envoy/Dockerfile
      args:
        - UPSTREAM=userservice.gstaad
    ports:
      - 9100:80
      - 9101:8081
    env_file: "src/userservice/.env"
    healthcheck:
      interval: 5s
      timeout: 2s
      retries: 4