version: '3'

services:
  postservice.gstaad:
    build:
      context: src/postservice
      dockerfile: Dockerfile
    ports:
      - 9202:8080
    environment:
      - APP_ENV=production
      - PORT=8080
    healthcheck:
      test: ["CMD-SHELL", "/bin/grpc_health_probe -addr=:8080 || exit 1"]
      interval: 5s
      timeout: 2s
      retries: 2
  postservice-gw.gstaad:
    build:
      context: src/postservice
      dockerfile: Dockerfile.gw
    ports:
      - 9200:80
      - 9201:8081
    healthcheck:
      interval: 5s
      timeout: 2s
      retries: 4
  userservice.gstaad:
    healthcheck:
      test: ["CMD-SHELL", "/bin/grpc_health_probe -addr=:8080 || exit 1"]
      interval: 5s
      timeout: 2s
      retries: 2
    build:
      context: src/userservice
      dockerfile: Dockerfile
    ports:
      - 9102:8080
    environment:
      - APP_ENV=production
      - PORT=8080
      - POSTSERVICE=dns:///postservice-gw.gstaad:80
  userservice-gw.gstaad:
    healthcheck:
      interval: 5s
      timeout: 2s
      retries: 4
    build:
      context: src/userservice
      dockerfile: Dockerfile.gw
    ports:
      - 9100:80
      - 9101:8081