version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@3.0.0
  aws-ecs: circleci/aws-ecs@0.0.6
executors:
  default:
    machine:
      enabled: true
      docker_layer_caching: true
  golang:
    docker:
      - image: circleci/golang
jobs:
  build_and_deploy:
    executor: <<parameters.executor>>
    environment:
      stage: develop
    parameters:
      executor:
        type: executor
        default: default
      svc_name:
        type: string
      svc_path:
        type: string
      build_steps:
        type: steps
        default: []
    steps:
      - checkout
      - restore_cache:
          keys:
            - gstaad-{{ .Branch }}
      - run:
          command: |
            mkdir -p .meta
            touch .meta/<<parameters.svc_name>>.hash
            git log --pretty=format:'%H' -n 1 -- <<parameters.svc_path>> > .meta/<<parameters.svc_name>>.hash.new
            ! diff .meta/<<parameters.svc_name>>.hash{,.new} > /dev/null
      - setup_remote_docker
      - steps: <<parameters.build_steps>>
      - aws-ecs/update-service:
          family: gstaad-<<parameters.svc_name>>
          cluster-name: gstaad
          service-name: <<parameters.svc_name>>
      - save_cache:
          key: gstaad-{{ .Branch }}-{{ epoch }}
          paths:
            - .meta
workflows:
  deploy_post:
    jobs:
      - build_and_deploy:
          executor: golang
          svc_name: post
          svc_path: svc/post
          build_steps:
            - aws-ecr/build-and-push-image:
                dockerfile: svc/post/Dockerfile
                repo: gstaad/post
                tag: ${CIRCLE_BRANCH}
  deploy_user:
    jobs:
      - build_and_deploy:
          executor: golang
          svc_name: user
          svc_path: svc/user
          build_steps:
            - aws-ecr/build-and-push-image:
                dockerfile: svc/user/Dockerfile
                repo: gstaad/user
                tag: ${CIRCLE_BRANCH}
  deploy_gateway:
    jobs:
      - build_and_deploy:
          executor: golang
          svc_name: gateway
          svc_path: svc/gateway
          build_steps:
            - aws-ecr/build-and-push-image:
                dockerfile: svc/gateway/Dockerfile
                repo: gstaad/gateway
                tag: ${CIRCLE_BRANCH}