version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@3.0.0
  aws-ecs: circleci/aws-ecs@0.0.6
executors:
  default:
    machine:
      enabled: true
      docker_layer_caching: true
  golang:
    docker:
      - image: circleci/golang
jobs:
  build_and_deploy:
    executor: <<parameters.executor>>
    environment:
      stage: develop
    parameters:
      executor:
        type: executor
        default: default
      svc_name:
        type: string
      svc_path:
        type: string
    steps:
      - checkout
      - restore_cache:
          keys:
            - gstaad-{{ .Branch }}
      - run:
          command: |
            mkdir -p .meta
            touch .meta/<<parameters.svc_name>>.hash
            git log --pretty=format:'%H' -n 1 -- <<parameters.svc_path>> > .meta/<<parameters.svc_name>>.hash.new
            ! diff .meta/<<parameters.svc_name>>.hash{,.new} > /dev/null
      - setup_remote_docker
      - aws-ecr/build-and-push-image:
          dockerfile: <<parameters.svc_path>>/Dockerfile
          repo: gstaad/<<parameters.svc_name>>
          tag: ${CIRCLE_BRANCH}
      - aws-ecs/update-service:
          family: gstaad-<<parameters.svc_name>>
          cluster-name: gstaad
      - save_cache:
          key: gstaad-{{ .Branch }}-{{ epoch }}
          paths:
            - .meta
workflows:
  build_post:
    jobs:
      - build_and_deploy:
          executor: golang
          svc_name: post
          svc_path: svc/post
  build_user:
    jobs:
      - build_and_deploy:
          executor: golang
          svc_name: user
          svc_path: svc/user